site_name: OpenAI Katas — Learn GenAI by Katas
site_description: Learn the OpenAI API platform and modern GenAI builder patterns through focused katas.
site_url: https://ozgurgulerx.github.io/openai-katas
repo_url: https://github.com/ozgurgulerx/openai-katas
repo_name: ozgurgulerx/openai-katas
edit_uri: ""

theme:
  name: material
  language: en
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.view
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - announce.dismiss
    - icon.admonition
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Light mode
  icon:
    logo: material/school
  favicon: material/library

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      allow_errors: false
      kernel_name: python3
      ignore_h1_titles: true
      include: ["*.ipynb", "*.py"]
      include_source: true
      include_requirejs: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.snippets

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: simple/github
      link: https://github.com/ozgurgulerx

nav:
  - Home: index.md
  - Katas: katas.md